//
//  VanStyleKit.m
//  ProjectName
//
//  Created by Marc Humet on 13/10/14.
//  Copyright (c) 2014 EQUUS LIFE SL. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "VanStyleKit.h"


@implementation VanStyleKit

#pragma mark Cache

static UIColor* _lletraEquus = nil;
static UIColor* _vermellEquus = nil;
static UIColor* _blancCavall = nil;
static UIColor* _negre = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _lletraEquus = [UIColor colorWithRed: 0.435 green: 0.416 blue: 0.408 alpha: 1];
    _vermellEquus = [UIColor colorWithRed: 1 green: 0.4 blue: 0.4 alpha: 1];
    _blancCavall = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _negre = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)lletraEquus { return _lletraEquus; }
+ (UIColor*)vermellEquus { return _vermellEquus; }
+ (UIColor*)blancCavall { return _blancCavall; }
+ (UIColor*)negre { return _negre; }

#pragma mark Drawing Methods

+ (void)drawCanvas1;
{

    //// Group
    {
        //// Group 2
        {
            //// Rectangle 2 Drawing
            UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(36.99, 1.65, 180.95, 180.94)];
            [VanStyleKit.vermellEquus setFill];
            [rectangle2Path fill];


            //// Bezier 2 Drawing
            UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
            [bezier2Path moveToPoint: CGPointMake(176.5, 54.98)];
            [bezier2Path addCurveToPoint: CGPointMake(171.36, 56.76) controlPoint1: CGPointMake(176.39, 54.79) controlPoint2: CGPointMake(172.59, 55.86)];
            [bezier2Path addCurveToPoint: CGPointMake(160.41, 54.2) controlPoint1: CGPointMake(169.6, 55.74) controlPoint2: CGPointMake(164.97, 54.2)];
            [bezier2Path addCurveToPoint: CGPointMake(137.43, 74.21) controlPoint1: CGPointMake(154, 54.2) controlPoint2: CGPointMake(145.95, 57.04)];
            [bezier2Path addCurveToPoint: CGPointMake(126.65, 78.67) controlPoint1: CGPointMake(137.18, 74.63) controlPoint2: CGPointMake(134.49, 78.67)];
            [bezier2Path addCurveToPoint: CGPointMake(114.22, 76.69) controlPoint1: CGPointMake(123.03, 78.67) controlPoint2: CGPointMake(118.86, 78.44)];
            [bezier2Path addCurveToPoint: CGPointMake(106.84, 75.52) controlPoint1: CGPointMake(114.08, 76.65) controlPoint2: CGPointMake(110.85, 75.52)];
            [bezier2Path addCurveToPoint: CGPointMake(96.14, 79.01) controlPoint1: CGPointMake(102.31, 75.52) controlPoint2: CGPointMake(98.71, 76.27)];
            [bezier2Path addCurveToPoint: CGPointMake(87.11, 75.06) controlPoint1: CGPointMake(90.94, 74.9) controlPoint2: CGPointMake(87.6, 75.06)];
            [bezier2Path addCurveToPoint: CGPointMake(77.37, 83.5) controlPoint1: CGPointMake(84.26, 75.06) controlPoint2: CGPointMake(78.13, 77.13)];
            [bezier2Path addCurveToPoint: CGPointMake(79.72, 91.93) controlPoint1: CGPointMake(76.95, 87.12) controlPoint2: CGPointMake(78.48, 89.79)];
            [bezier2Path addCurveToPoint: CGPointMake(80.46, 96.28) controlPoint1: CGPointMake(80.97, 94.11) controlPoint2: CGPointMake(81.52, 95.2)];
            [bezier2Path addCurveToPoint: CGPointMake(80.36, 97.05) controlPoint1: CGPointMake(80.26, 96.5) controlPoint2: CGPointMake(80.22, 96.8)];
            [bezier2Path addCurveToPoint: CGPointMake(80.92, 97.38) controlPoint1: CGPointMake(80.48, 97.26) controlPoint2: CGPointMake(80.69, 97.38)];
            [bezier2Path addCurveToPoint: CGPointMake(81.07, 97.37) controlPoint1: CGPointMake(80.97, 97.38) controlPoint2: CGPointMake(81.02, 97.38)];
            [bezier2Path addCurveToPoint: CGPointMake(86.4, 92.98) controlPoint1: CGPointMake(81.27, 97.32) controlPoint2: CGPointMake(86.22, 96.16)];
            [bezier2Path addCurveToPoint: CGPointMake(86.14, 90.05) controlPoint1: CGPointMake(86.45, 92.24) controlPoint2: CGPointMake(86.3, 91.23)];
            [bezier2Path addCurveToPoint: CGPointMake(86.39, 83.68) controlPoint1: CGPointMake(85.83, 87.85) controlPoint2: CGPointMake(85.4, 84.82)];
            [bezier2Path addCurveToPoint: CGPointMake(88.39, 83.25) controlPoint1: CGPointMake(86.78, 83.22) controlPoint2: CGPointMake(87.46, 83.08)];
            [bezier2Path addCurveToPoint: CGPointMake(91.34, 83.54) controlPoint1: CGPointMake(89.47, 83.44) controlPoint2: CGPointMake(90.47, 83.54)];
            [bezier2Path addCurveToPoint: CGPointMake(93.45, 83.3) controlPoint1: CGPointMake(92.2, 83.54) controlPoint2: CGPointMake(92.89, 83.45)];
            [bezier2Path addCurveToPoint: CGPointMake(91.87, 96.41) controlPoint1: CGPointMake(92.04, 86.69) controlPoint2: CGPointMake(91.51, 91.08)];
            [bezier2Path addCurveToPoint: CGPointMake(91.97, 96.71) controlPoint1: CGPointMake(91.88, 96.51) controlPoint2: CGPointMake(91.91, 96.61)];
            [bezier2Path addCurveToPoint: CGPointMake(93.02, 103.92) controlPoint1: CGPointMake(91.99, 96.75) controlPoint2: CGPointMake(94.35, 100.55)];
            [bezier2Path addCurveToPoint: CGPointMake(86.5, 108.51) controlPoint1: CGPointMake(92.16, 106.06) controlPoint2: CGPointMake(89.97, 107.61)];
            [bezier2Path addCurveToPoint: CGPointMake(86.34, 108.57) controlPoint1: CGPointMake(86.45, 108.52) controlPoint2: CGPointMake(86.39, 108.55)];
            [bezier2Path addCurveToPoint: CGPointMake(83.65, 112.34) controlPoint1: CGPointMake(86.26, 108.63) controlPoint2: CGPointMake(84.17, 109.82)];
            [bezier2Path addCurveToPoint: CGPointMake(83.31, 114.39) controlPoint1: CGPointMake(83.55, 112.8) controlPoint2: CGPointMake(83.45, 113.5)];
            [bezier2Path addCurveToPoint: CGPointMake(79.62, 127.51) controlPoint1: CGPointMake(82.78, 117.89) controlPoint2: CGPointMake(81.81, 125.04)];
            [bezier2Path addCurveToPoint: CGPointMake(79.53, 130.74) controlPoint1: CGPointMake(79.56, 127.56) controlPoint2: CGPointMake(78.85, 129.64)];
            [bezier2Path addCurveToPoint: CGPointMake(80.6, 131.5) controlPoint1: CGPointMake(79.77, 131.13) controlPoint2: CGPointMake(80.14, 131.39)];
            [bezier2Path addCurveToPoint: CGPointMake(81.18, 132.64) controlPoint1: CGPointMake(80.95, 131.94) controlPoint2: CGPointMake(81.24, 132.47)];
            [bezier2Path addCurveToPoint: CGPointMake(79.9, 134.6) controlPoint1: CGPointMake(80.47, 133.09) controlPoint2: CGPointMake(79.99, 133.82)];
            [bezier2Path addCurveToPoint: CGPointMake(80.6, 136.51) controlPoint1: CGPointMake(79.82, 135.3) controlPoint2: CGPointMake(80.07, 135.98)];
            [bezier2Path addCurveToPoint: CGPointMake(86.36, 138.06) controlPoint1: CGPointMake(81.42, 137.34) controlPoint2: CGPointMake(84.12, 138.06)];
            [bezier2Path addCurveToPoint: CGPointMake(89.26, 137.45) controlPoint1: CGPointMake(87.59, 138.06) controlPoint2: CGPointMake(88.56, 137.86)];
            [bezier2Path addCurveToPoint: CGPointMake(89.52, 136.64) controlPoint1: CGPointMake(89.54, 137.28) controlPoint2: CGPointMake(89.65, 136.94)];
            [bezier2Path addCurveToPoint: CGPointMake(86.31, 131.34) controlPoint1: CGPointMake(89.48, 136.52) controlPoint2: CGPointMake(88.32, 133.75)];
            [bezier2Path addCurveToPoint: CGPointMake(86.32, 127.53) controlPoint1: CGPointMake(86.19, 130.8) controlPoint2: CGPointMake(85.87, 128.91)];
            [bezier2Path addCurveToPoint: CGPointMake(86.34, 127.21) controlPoint1: CGPointMake(86.36, 127.44) controlPoint2: CGPointMake(86.36, 127.32)];
            [bezier2Path addCurveToPoint: CGPointMake(98.08, 111.3) controlPoint1: CGPointMake(86.32, 127.11) controlPoint2: CGPointMake(84.58, 116.89)];
            [bezier2Path addCurveToPoint: CGPointMake(103.85, 108.41) controlPoint1: CGPointMake(98.54, 111.2) controlPoint2: CGPointMake(101.3, 110.49)];
            [bezier2Path addCurveToPoint: CGPointMake(102.66, 110.28) controlPoint1: CGPointMake(103.7, 109.06) controlPoint2: CGPointMake(103.37, 109.8)];
            [bezier2Path addCurveToPoint: CGPointMake(97.47, 113.9) controlPoint1: CGPointMake(100.74, 111.59) controlPoint2: CGPointMake(97.52, 113.86)];
            [bezier2Path addCurveToPoint: CGPointMake(96.63, 116.12) controlPoint1: CGPointMake(97.04, 114.28) controlPoint2: CGPointMake(96.38, 115.16)];
            [bezier2Path addCurveToPoint: CGPointMake(100.27, 118.36) controlPoint1: CGPointMake(96.9, 117.18) controlPoint2: CGPointMake(98.09, 117.92)];
            [bezier2Path addCurveToPoint: CGPointMake(109.55, 126.29) controlPoint1: CGPointMake(105.12, 119.38) controlPoint2: CGPointMake(109.33, 124.51)];
            [bezier2Path addCurveToPoint: CGPointMake(109.59, 126.47) controlPoint1: CGPointMake(109.55, 126.35) controlPoint2: CGPointMake(109.57, 126.41)];
            [bezier2Path addCurveToPoint: CGPointMake(111.07, 128.21) controlPoint1: CGPointMake(109.7, 126.72) controlPoint2: CGPointMake(110.23, 127.85)];
            [bezier2Path addCurveToPoint: CGPointMake(110.77, 128.72) controlPoint1: CGPointMake(111.03, 128.43) controlPoint2: CGPointMake(110.93, 128.66)];
            [bezier2Path addCurveToPoint: CGPointMake(110.38, 129.39) controlPoint1: CGPointMake(110.51, 128.83) controlPoint2: CGPointMake(110.36, 129.11)];
            [bezier2Path addCurveToPoint: CGPointMake(117.35, 135.21) controlPoint1: CGPointMake(110.41, 129.58) controlPoint2: CGPointMake(110.99, 133.93)];
            [bezier2Path addCurveToPoint: CGPointMake(117.86, 135.09) controlPoint1: CGPointMake(117.53, 135.23) controlPoint2: CGPointMake(117.72, 135.19)];
            [bezier2Path addCurveToPoint: CGPointMake(118.12, 134.63) controlPoint1: CGPointMake(118.01, 134.98) controlPoint2: CGPointMake(118.1, 134.81)];
            [bezier2Path addCurveToPoint: CGPointMake(117.84, 126.94) controlPoint1: CGPointMake(118.17, 134.05) controlPoint2: CGPointMake(118.54, 128.95)];
            [bezier2Path addCurveToPoint: CGPointMake(117.31, 125.97) controlPoint1: CGPointMake(117.65, 126.39) controlPoint2: CGPointMake(117.65, 126.15)];
            [bezier2Path addCurveToPoint: CGPointMake(107.67, 116.41) controlPoint1: CGPointMake(113.12, 123.76) controlPoint2: CGPointMake(110.39, 120.11)];
            [bezier2Path addCurveToPoint: CGPointMake(107.55, 115.34) controlPoint1: CGPointMake(107.58, 116.2) controlPoint2: CGPointMake(107.43, 115.77)];
            [bezier2Path addCurveToPoint: CGPointMake(108.68, 114.26) controlPoint1: CGPointMake(107.67, 114.92) controlPoint2: CGPointMake(108.05, 114.56)];
            [bezier2Path addCurveToPoint: CGPointMake(109.87, 113.74) controlPoint1: CGPointMake(109.02, 114.09) controlPoint2: CGPointMake(109.42, 113.92)];
            [bezier2Path addCurveToPoint: CGPointMake(118.2, 105.97) controlPoint1: CGPointMake(112.56, 112.61) controlPoint2: CGPointMake(116.96, 110.75)];
            [bezier2Path addCurveToPoint: CGPointMake(135.77, 107.9) controlPoint1: CGPointMake(119.95, 106.36) controlPoint2: CGPointMake(127.98, 107.9)];
            [bezier2Path addCurveToPoint: CGPointMake(133.42, 117.47) controlPoint1: CGPointMake(135.77, 107.9) controlPoint2: CGPointMake(133.42, 117.42)];
            [bezier2Path addCurveToPoint: CGPointMake(133.55, 119.32) controlPoint1: CGPointMake(133.42, 117.59) controlPoint2: CGPointMake(133.43, 118.67)];
            [bezier2Path addCurveToPoint: CGPointMake(129.84, 128.24) controlPoint1: CGPointMake(132.99, 122.7) controlPoint2: CGPointMake(130.32, 127)];
            [bezier2Path addCurveToPoint: CGPointMake(131, 132.23) controlPoint1: CGPointMake(129.24, 129.85) controlPoint2: CGPointMake(130.03, 131.66)];
            [bezier2Path addCurveToPoint: CGPointMake(131.2, 132.37) controlPoint1: CGPointMake(131.12, 132.31) controlPoint2: CGPointMake(131.18, 132.39)];
            [bezier2Path addCurveToPoint: CGPointMake(131.11, 132.44) controlPoint1: CGPointMake(131.18, 132.38) controlPoint2: CGPointMake(131.16, 132.41)];
            [bezier2Path addCurveToPoint: CGPointMake(130.83, 132.79) controlPoint1: CGPointMake(130.98, 132.52) controlPoint2: CGPointMake(130.88, 132.63)];
            [bezier2Path addCurveToPoint: CGPointMake(131.25, 136.8) controlPoint1: CGPointMake(130.63, 133.41) controlPoint2: CGPointMake(130.05, 136.12)];
            [bezier2Path addCurveToPoint: CGPointMake(138.11, 137.99) controlPoint1: CGPointMake(131.94, 137.2) controlPoint2: CGPointMake(135.29, 137.99)];
            [bezier2Path addCurveToPoint: CGPointMake(139.72, 137.8) controlPoint1: CGPointMake(138.71, 137.99) controlPoint2: CGPointMake(139.24, 137.93)];
            [bezier2Path addCurveToPoint: CGPointMake(140.14, 137.47) controlPoint1: CGPointMake(139.9, 137.75) controlPoint2: CGPointMake(140.06, 137.63)];
            [bezier2Path addCurveToPoint: CGPointMake(140.17, 136.95) controlPoint1: CGPointMake(140.22, 137.31) controlPoint2: CGPointMake(140.24, 137.12)];
            [bezier2Path addCurveToPoint: CGPointMake(137.51, 131.67) controlPoint1: CGPointMake(139.4, 134.91) controlPoint2: CGPointMake(138.36, 132.47)];
            [bezier2Path addCurveToPoint: CGPointMake(136.52, 125.94) controlPoint1: CGPointMake(136.64, 129.48) controlPoint2: CGPointMake(136.2, 129.65)];
            [bezier2Path addCurveToPoint: CGPointMake(138.33, 120.65) controlPoint1: CGPointMake(136.75, 123.3) controlPoint2: CGPointMake(138.16, 121.21)];
            [bezier2Path addCurveToPoint: CGPointMake(140.57, 117.97) controlPoint1: CGPointMake(139.02, 120.26) controlPoint2: CGPointMake(140.12, 119.82)];
            [bezier2Path addCurveToPoint: CGPointMake(146.46, 107.95) controlPoint1: CGPointMake(140.68, 116.91) controlPoint2: CGPointMake(145.3, 110.02)];
            [bezier2Path addCurveToPoint: CGPointMake(167.83, 107.38) controlPoint1: CGPointMake(152.18, 107.9) controlPoint2: CGPointMake(158.64, 108.01)];
            [bezier2Path addLineToPoint: CGPointMake(168.04, 109.22)];
            [bezier2Path addCurveToPoint: CGPointMake(165.13, 116.23) controlPoint1: CGPointMake(167.82, 110.94) controlPoint2: CGPointMake(166.92, 115.13)];
            [bezier2Path addCurveToPoint: CGPointMake(164.83, 116.87) controlPoint1: CGPointMake(164.92, 116.37) controlPoint2: CGPointMake(164.81, 116.61)];
            [bezier2Path addCurveToPoint: CGPointMake(164.75, 118.06) controlPoint1: CGPointMake(164.9, 117.34) controlPoint2: CGPointMake(164.85, 117.96)];
            [bezier2Path addCurveToPoint: CGPointMake(163.88, 117.74) controlPoint1: CGPointMake(164.53, 118.06) controlPoint2: CGPointMake(164.17, 117.89)];
            [bezier2Path addCurveToPoint: CGPointMake(162.73, 117.37) controlPoint1: CGPointMake(163.49, 117.56) controlPoint2: CGPointMake(163.11, 117.37)];
            [bezier2Path addCurveToPoint: CGPointMake(162.11, 117.57) controlPoint1: CGPointMake(162.49, 117.37) controlPoint2: CGPointMake(162.28, 117.45)];
            [bezier2Path addCurveToPoint: CGPointMake(160.88, 126.58) controlPoint1: CGPointMake(161.38, 118.14) controlPoint2: CGPointMake(158.88, 123.65)];
            [bezier2Path addCurveToPoint: CGPointMake(161.71, 126.8) controlPoint1: CGPointMake(161.07, 126.85) controlPoint2: CGPointMake(161.42, 126.94)];
            [bezier2Path addCurveToPoint: CGPointMake(168.22, 122.05) controlPoint1: CGPointMake(162.28, 126.5) controlPoint2: CGPointMake(167.3, 123.89)];
            [bezier2Path addLineToPoint: CGPointMake(169.78, 118.44)];
            [bezier2Path addCurveToPoint: CGPointMake(174.48, 106.26) controlPoint1: CGPointMake(170.63, 114.14) controlPoint2: CGPointMake(174.44, 106.33)];
            [bezier2Path addCurveToPoint: CGPointMake(174.14, 102.21) controlPoint1: CGPointMake(174.65, 105.77) controlPoint2: CGPointMake(175.41, 104.17)];
            [bezier2Path addCurveToPoint: CGPointMake(172.45, 101.24) controlPoint1: CGPointMake(173.75, 101.63) controlPoint2: CGPointMake(173.18, 101.3)];
            [bezier2Path addCurveToPoint: CGPointMake(161.25, 99.5) controlPoint1: CGPointMake(168.46, 100.94) controlPoint2: CGPointMake(162.22, 100.71)];
            [bezier2Path addCurveToPoint: CGPointMake(161.28, 75.74) controlPoint1: CGPointMake(161.29, 93.03) controlPoint2: CGPointMake(161.24, 83.2)];
            [bezier2Path addCurveToPoint: CGPointMake(163.08, 73.78) controlPoint1: CGPointMake(161.3, 75.72) controlPoint2: CGPointMake(163.06, 73.82)];
            [bezier2Path addCurveToPoint: CGPointMake(164.93, 77.62) controlPoint1: CGPointMake(163.35, 74.4) controlPoint2: CGPointMake(164.12, 75.99)];
            [bezier2Path addCurveToPoint: CGPointMake(164.69, 78.93) controlPoint1: CGPointMake(164.78, 78.02) controlPoint2: CGPointMake(164.69, 78.46)];
            [bezier2Path addCurveToPoint: CGPointMake(167.55, 82.57) controlPoint1: CGPointMake(164.69, 80.69) controlPoint2: CGPointMake(165.91, 82.16)];
            [bezier2Path addCurveToPoint: CGPointMake(171.56, 82.68) controlPoint1: CGPointMake(167.57, 82.57) controlPoint2: CGPointMake(169.8, 82.98)];
            [bezier2Path addCurveToPoint: CGPointMake(172.75, 81.33) controlPoint1: CGPointMake(172.57, 82.5) controlPoint2: CGPointMake(172.75, 81.38)];
            [bezier2Path addCurveToPoint: CGPointMake(173.86, 59.59) controlPoint1: CGPointMake(174.69, 72.73) controlPoint2: CGPointMake(174.77, 66.63)];
            [bezier2Path addCurveToPoint: CGPointMake(176.47, 55.59) controlPoint1: CGPointMake(175.73, 57.15) controlPoint2: CGPointMake(176.39, 55.73)];
            [bezier2Path addCurveToPoint: CGPointMake(176.5, 54.98) controlPoint1: CGPointMake(176.58, 55.41) controlPoint2: CGPointMake(176.59, 55.18)];
            [bezier2Path closePath];
            bezier2Path.miterLimit = 4;

            [VanStyleKit.blancCavall setFill];
            [bezier2Path fill];
        }


        //// Group 3
        {
            //// Bezier 4 Drawing
            UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
            [bezier4Path moveToPoint: CGPointMake(257.64, 96.59)];
            [bezier4Path addLineToPoint: CGPointMake(249.22, 96.59)];
            [bezier4Path addLineToPoint: CGPointMake(249.22, 134.72)];
            [bezier4Path addLineToPoint: CGPointMake(276.61, 134.72)];
            [bezier4Path addLineToPoint: CGPointMake(276.61, 127)];
            [bezier4Path addLineToPoint: CGPointMake(257.64, 127)];
            [bezier4Path addLineToPoint: CGPointMake(257.64, 96.59)];
            [bezier4Path closePath];
            bezier4Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier4Path fill];


            //// Rectangle 4 Drawing
            UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRect: CGRectMake(280.57, 96.59, 8.35, 38.13)];
            [VanStyleKit.lletraEquus setFill];
            [rectangle4Path fill];


            //// Bezier 6 Drawing
            UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
            [bezier6Path moveToPoint: CGPointMake(295.76, 134.72)];
            [bezier6Path addLineToPoint: CGPointMake(304.15, 134.72)];
            [bezier6Path addLineToPoint: CGPointMake(304.15, 119.9)];
            [bezier6Path addLineToPoint: CGPointMake(322.23, 119.9)];
            [bezier6Path addLineToPoint: CGPointMake(322.23, 112.3)];
            [bezier6Path addLineToPoint: CGPointMake(304.15, 112.3)];
            [bezier6Path addLineToPoint: CGPointMake(304.15, 104.22)];
            [bezier6Path addLineToPoint: CGPointMake(324.72, 104.22)];
            [bezier6Path addLineToPoint: CGPointMake(324.72, 96.59)];
            [bezier6Path addLineToPoint: CGPointMake(295.76, 96.59)];
            [bezier6Path addLineToPoint: CGPointMake(295.76, 134.72)];
            [bezier6Path closePath];
            bezier6Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier6Path fill];


            //// Bezier 8 Drawing
            UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
            [bezier8Path moveToPoint: CGPointMake(337, 119.22)];
            [bezier8Path addLineToPoint: CGPointMake(354.95, 119.22)];
            [bezier8Path addLineToPoint: CGPointMake(354.95, 111.78)];
            [bezier8Path addLineToPoint: CGPointMake(337, 111.78)];
            [bezier8Path addLineToPoint: CGPointMake(337, 104.05)];
            [bezier8Path addLineToPoint: CGPointMake(357.34, 104.05)];
            [bezier8Path addLineToPoint: CGPointMake(357.34, 96.59)];
            [bezier8Path addLineToPoint: CGPointMake(328.69, 96.59)];
            [bezier8Path addLineToPoint: CGPointMake(328.69, 134.72)];
            [bezier8Path addLineToPoint: CGPointMake(357.67, 134.72)];
            [bezier8Path addLineToPoint: CGPointMake(357.67, 127.25)];
            [bezier8Path addLineToPoint: CGPointMake(337, 127.25)];
            [bezier8Path addLineToPoint: CGPointMake(337, 119.22)];
            [bezier8Path closePath];
            bezier8Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier8Path fill];


            //// Bezier 10 Drawing
            UIBezierPath* bezier10Path = UIBezierPath.bezierPath;
            [bezier10Path moveToPoint: CGPointMake(257.52, 72.81)];
            [bezier10Path addLineToPoint: CGPointMake(275.47, 72.81)];
            [bezier10Path addLineToPoint: CGPointMake(275.47, 65.36)];
            [bezier10Path addLineToPoint: CGPointMake(257.52, 65.36)];
            [bezier10Path addLineToPoint: CGPointMake(257.52, 57.66)];
            [bezier10Path addLineToPoint: CGPointMake(277.96, 57.66)];
            [bezier10Path addLineToPoint: CGPointMake(277.96, 50.19)];
            [bezier10Path addLineToPoint: CGPointMake(249.22, 50.19)];
            [bezier10Path addLineToPoint: CGPointMake(249.22, 88.25)];
            [bezier10Path addLineToPoint: CGPointMake(278.2, 88.25)];
            [bezier10Path addLineToPoint: CGPointMake(278.2, 80.81)];
            [bezier10Path addLineToPoint: CGPointMake(257.52, 80.81)];
            [bezier10Path addLineToPoint: CGPointMake(257.52, 72.81)];
            [bezier10Path closePath];
            bezier10Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier10Path fill];


            //// Bezier 12 Drawing
            UIBezierPath* bezier12Path = UIBezierPath.bezierPath;
            [bezier12Path moveToPoint: CGPointMake(350.62, 72.02)];
            [bezier12Path addCurveToPoint: CGPointMake(342.37, 81.14) controlPoint1: CGPointMake(350.62, 78) controlPoint2: CGPointMake(347.57, 81.14)];
            [bezier12Path addCurveToPoint: CGPointMake(334.22, 71.7) controlPoint1: CGPointMake(337.32, 81.14) controlPoint2: CGPointMake(334.22, 77.94)];
            [bezier12Path addLineToPoint: CGPointMake(334.22, 50.19)];
            [bezier12Path addLineToPoint: CGPointMake(325.78, 50.19)];
            [bezier12Path addLineToPoint: CGPointMake(325.78, 71.93)];
            [bezier12Path addCurveToPoint: CGPointMake(342.3, 88.9) controlPoint1: CGPointMake(325.78, 83.15) controlPoint2: CGPointMake(332.12, 88.9)];
            [bezier12Path addCurveToPoint: CGPointMake(359, 71.7) controlPoint1: CGPointMake(352.58, 88.9) controlPoint2: CGPointMake(359, 83.19)];
            [bezier12Path addLineToPoint: CGPointMake(359, 50.19)];
            [bezier12Path addLineToPoint: CGPointMake(350.62, 50.19)];
            [bezier12Path addLineToPoint: CGPointMake(350.62, 72.02)];
            [bezier12Path closePath];
            bezier12Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier12Path fill];


            //// Bezier 14 Drawing
            UIBezierPath* bezier14Path = UIBezierPath.bezierPath;
            [bezier14Path moveToPoint: CGPointMake(388.98, 72.02)];
            [bezier14Path addCurveToPoint: CGPointMake(380.77, 81.14) controlPoint1: CGPointMake(388.98, 78) controlPoint2: CGPointMake(385.91, 81.14)];
            [bezier14Path addCurveToPoint: CGPointMake(372.55, 71.7) controlPoint1: CGPointMake(375.71, 81.14) controlPoint2: CGPointMake(372.55, 77.94)];
            [bezier14Path addLineToPoint: CGPointMake(372.55, 50.19)];
            [bezier14Path addLineToPoint: CGPointMake(364.18, 50.19)];
            [bezier14Path addLineToPoint: CGPointMake(364.18, 71.93)];
            [bezier14Path addCurveToPoint: CGPointMake(380.71, 88.9) controlPoint1: CGPointMake(364.18, 83.15) controlPoint2: CGPointMake(370.45, 88.9)];
            [bezier14Path addCurveToPoint: CGPointMake(397.41, 71.7) controlPoint1: CGPointMake(390.92, 88.9) controlPoint2: CGPointMake(397.41, 83.19)];
            [bezier14Path addLineToPoint: CGPointMake(397.41, 50.19)];
            [bezier14Path addLineToPoint: CGPointMake(388.98, 50.19)];
            [bezier14Path addLineToPoint: CGPointMake(388.98, 72.02)];
            [bezier14Path closePath];
            bezier14Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier14Path fill];


            //// Bezier 16 Drawing
            UIBezierPath* bezier16Path = UIBezierPath.bezierPath;
            [bezier16Path moveToPoint: CGPointMake(418.68, 65.48)];
            [bezier16Path addCurveToPoint: CGPointMake(410.43, 60.46) controlPoint1: CGPointMake(412.08, 63.78) controlPoint2: CGPointMake(410.43, 63)];
            [bezier16Path addLineToPoint: CGPointMake(410.43, 60.35)];
            [bezier16Path addCurveToPoint: CGPointMake(415.3, 56.99) controlPoint1: CGPointMake(410.43, 58.5) controlPoint2: CGPointMake(412.11, 56.99)];
            [bezier16Path addCurveToPoint: CGPointMake(425.24, 60.78) controlPoint1: CGPointMake(418.51, 56.99) controlPoint2: CGPointMake(421.84, 58.48)];
            [bezier16Path addLineToPoint: CGPointMake(429.55, 54.5)];
            [bezier16Path addCurveToPoint: CGPointMake(415.41, 49.66) controlPoint1: CGPointMake(425.71, 51.38) controlPoint2: CGPointMake(420.93, 49.66)];
            [bezier16Path addCurveToPoint: CGPointMake(402.09, 61.12) controlPoint1: CGPointMake(407.65, 49.66) controlPoint2: CGPointMake(402.09, 54.17)];
            [bezier16Path addLineToPoint: CGPointMake(402.09, 61.24)];
            [bezier16Path addCurveToPoint: CGPointMake(414.74, 72.88) controlPoint1: CGPointMake(402.09, 68.84) controlPoint2: CGPointMake(407.04, 70.92)];
            [bezier16Path addCurveToPoint: CGPointMake(422.42, 77.76) controlPoint1: CGPointMake(421.08, 74.49) controlPoint2: CGPointMake(422.42, 75.61)];
            [bezier16Path addLineToPoint: CGPointMake(422.42, 77.86)];
            [bezier16Path addCurveToPoint: CGPointMake(416.92, 81.37) controlPoint1: CGPointMake(422.42, 80.05) controlPoint2: CGPointMake(420.31, 81.37)];
            [bezier16Path addCurveToPoint: CGPointMake(405.55, 76.78) controlPoint1: CGPointMake(412.55, 81.37) controlPoint2: CGPointMake(408.95, 79.6)];
            [bezier16Path addLineToPoint: CGPointMake(400.59, 82.71)];
            [bezier16Path addCurveToPoint: CGPointMake(416.78, 88.82) controlPoint1: CGPointMake(405.2, 86.78) controlPoint2: CGPointMake(410.96, 88.82)];
            [bezier16Path addCurveToPoint: CGPointMake(430.73, 77) controlPoint1: CGPointMake(424.97, 88.82) controlPoint2: CGPointMake(430.73, 84.57)];
            [bezier16Path addLineToPoint: CGPointMake(430.73, 76.91)];
            [bezier16Path addCurveToPoint: CGPointMake(418.68, 65.48) controlPoint1: CGPointMake(430.73, 70.28) controlPoint2: CGPointMake(426.36, 67.47)];
            [bezier16Path closePath];
            bezier16Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier16Path fill];


            //// Bezier 18 Drawing
            UIBezierPath* bezier18Path = UIBezierPath.bezierPath;
            [bezier18Path moveToPoint: CGPointMake(301.43, 88.91)];
            [bezier18Path addCurveToPoint: CGPointMake(311.73, 86.32) controlPoint1: CGPointMake(305.26, 88.91) controlPoint2: CGPointMake(308.76, 87.97)];
            [bezier18Path addLineToPoint: CGPointMake(313.73, 88.54)];
            [bezier18Path addLineToPoint: CGPointMake(323.76, 88.54)];
            [bezier18Path addLineToPoint: CGPointMake(317.47, 81.51)];
            [bezier18Path addCurveToPoint: CGPointMake(321.79, 69.21) controlPoint1: CGPointMake(320.2, 78.14) controlPoint2: CGPointMake(321.79, 73.86)];
            [bezier18Path addLineToPoint: CGPointMake(321.79, 69.08)];
            [bezier18Path addCurveToPoint: CGPointMake(301.51, 49.53) controlPoint1: CGPointMake(321.79, 58.31) controlPoint2: CGPointMake(313.31, 49.53)];
            [bezier18Path addCurveToPoint: CGPointMake(281.22, 69.21) controlPoint1: CGPointMake(289.79, 49.53) controlPoint2: CGPointMake(281.22, 58.43)];
            [bezier18Path addLineToPoint: CGPointMake(281.22, 69.36)];
            [bezier18Path addCurveToPoint: CGPointMake(301.43, 88.91) controlPoint1: CGPointMake(281.22, 80.19) controlPoint2: CGPointMake(289.66, 88.91)];
            [bezier18Path closePath];
            [bezier18Path moveToPoint: CGPointMake(290.03, 69.08)];
            [bezier18Path addCurveToPoint: CGPointMake(301.43, 57.27) controlPoint1: CGPointMake(290.03, 62.59) controlPoint2: CGPointMake(294.65, 57.27)];
            [bezier18Path addCurveToPoint: CGPointMake(312.92, 69.21) controlPoint1: CGPointMake(308.13, 57.27) controlPoint2: CGPointMake(312.92, 62.68)];
            [bezier18Path addLineToPoint: CGPointMake(312.92, 69.36)];
            [bezier18Path addCurveToPoint: CGPointMake(301.51, 81.19) controlPoint1: CGPointMake(312.92, 75.85) controlPoint2: CGPointMake(308.31, 81.19)];
            [bezier18Path addCurveToPoint: CGPointMake(290.03, 69.21) controlPoint1: CGPointMake(294.8, 81.19) controlPoint2: CGPointMake(290.03, 75.74)];
            [bezier18Path addLineToPoint: CGPointMake(290.03, 69.08)];
            [bezier18Path closePath];
            bezier18Path.miterLimit = 4;

            [VanStyleKit.lletraEquus setFill];
            [bezier18Path fill];
        }
    }
}

+ (void)drawLogoEquusVertical;
{

    //// Group
    {
        //// Rectangle 2 Drawing
        UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(12.28, 10.21, 346.76, 346.76)];
        [VanStyleKit.vermellEquus setFill];
        [rectangle2Path fill];


        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(279.62, 112.4)];
        [bezier2Path addCurveToPoint: CGPointMake(269.78, 115.82) controlPoint1: CGPointMake(279.43, 112.04) controlPoint2: CGPointMake(272.15, 114.1)];
        [bezier2Path addCurveToPoint: CGPointMake(248.79, 110.92) controlPoint1: CGPointMake(266.42, 113.86) controlPoint2: CGPointMake(257.55, 110.92)];
        [bezier2Path addCurveToPoint: CGPointMake(204.77, 149.26) controlPoint1: CGPointMake(236.53, 110.92) controlPoint2: CGPointMake(221.09, 116.34)];
        [bezier2Path addCurveToPoint: CGPointMake(184.11, 157.8) controlPoint1: CGPointMake(204.29, 150.06) controlPoint2: CGPointMake(199.14, 157.8)];
        [bezier2Path addCurveToPoint: CGPointMake(160.29, 154.02) controlPoint1: CGPointMake(177.18, 157.8) controlPoint2: CGPointMake(169.17, 157.36)];
        [bezier2Path addCurveToPoint: CGPointMake(146.14, 151.77) controlPoint1: CGPointMake(160.03, 153.92) controlPoint2: CGPointMake(153.83, 151.77)];
        [bezier2Path addCurveToPoint: CGPointMake(125.64, 158.46) controlPoint1: CGPointMake(137.46, 151.77) controlPoint2: CGPointMake(130.56, 153.21)];
        [bezier2Path addCurveToPoint: CGPointMake(108.34, 150.88) controlPoint1: CGPointMake(115.67, 150.59) controlPoint2: CGPointMake(109.28, 150.88)];
        [bezier2Path addCurveToPoint: CGPointMake(89.68, 167.07) controlPoint1: CGPointMake(102.88, 150.88) controlPoint2: CGPointMake(91.13, 154.85)];
        [bezier2Path addCurveToPoint: CGPointMake(94.16, 183.22) controlPoint1: CGPointMake(88.86, 174) controlPoint2: CGPointMake(91.79, 179.12)];
        [bezier2Path addCurveToPoint: CGPointMake(95.6, 191.56) controlPoint1: CGPointMake(96.56, 187.39) controlPoint2: CGPointMake(97.61, 189.49)];
        [bezier2Path addCurveToPoint: CGPointMake(95.41, 193.04) controlPoint1: CGPointMake(95.21, 191.97) controlPoint2: CGPointMake(95.12, 192.55)];
        [bezier2Path addCurveToPoint: CGPointMake(96.48, 193.66) controlPoint1: CGPointMake(95.63, 193.43) controlPoint2: CGPointMake(96.04, 193.66)];
        [bezier2Path addCurveToPoint: CGPointMake(96.75, 193.64) controlPoint1: CGPointMake(96.56, 193.66) controlPoint2: CGPointMake(96.66, 193.66)];
        [bezier2Path addCurveToPoint: CGPointMake(106.98, 185.22) controlPoint1: CGPointMake(97.14, 193.54) controlPoint2: CGPointMake(106.62, 191.33)];
        [bezier2Path addCurveToPoint: CGPointMake(106.48, 179.61) controlPoint1: CGPointMake(107.08, 183.82) controlPoint2: CGPointMake(106.79, 181.87)];
        [bezier2Path addCurveToPoint: CGPointMake(106.96, 167.4) controlPoint1: CGPointMake(105.88, 175.39) controlPoint2: CGPointMake(105.07, 169.6)];
        [bezier2Path addCurveToPoint: CGPointMake(110.79, 166.58) controlPoint1: CGPointMake(107.71, 166.52) controlPoint2: CGPointMake(109, 166.26)];
        [bezier2Path addCurveToPoint: CGPointMake(116.45, 167.14) controlPoint1: CGPointMake(112.86, 166.95) controlPoint2: CGPointMake(114.77, 167.14)];
        [bezier2Path addCurveToPoint: CGPointMake(120.48, 166.68) controlPoint1: CGPointMake(118.09, 167.14) controlPoint2: CGPointMake(119.42, 166.96)];
        [bezier2Path addCurveToPoint: CGPointMake(117.46, 191.8) controlPoint1: CGPointMake(117.77, 173.19) controlPoint2: CGPointMake(116.76, 181.58)];
        [bezier2Path addCurveToPoint: CGPointMake(117.65, 192.38) controlPoint1: CGPointMake(117.48, 192) controlPoint2: CGPointMake(117.54, 192.19)];
        [bezier2Path addCurveToPoint: CGPointMake(119.66, 206.19) controlPoint1: CGPointMake(117.68, 192.45) controlPoint2: CGPointMake(122.2, 199.74)];
        [bezier2Path addCurveToPoint: CGPointMake(107.17, 215) controlPoint1: CGPointMake(118.02, 210.31) controlPoint2: CGPointMake(113.81, 213.27)];
        [bezier2Path addCurveToPoint: CGPointMake(106.86, 215.1) controlPoint1: CGPointMake(107.07, 215.02) controlPoint2: CGPointMake(106.96, 215.08)];
        [bezier2Path addCurveToPoint: CGPointMake(101.69, 222.34) controlPoint1: CGPointMake(106.71, 215.21) controlPoint2: CGPointMake(102.71, 217.5)];
        [bezier2Path addCurveToPoint: CGPointMake(101.05, 226.26) controlPoint1: CGPointMake(101.5, 223.21) controlPoint2: CGPointMake(101.31, 224.55)];
        [bezier2Path addCurveToPoint: CGPointMake(93.97, 251.39) controlPoint1: CGPointMake(100.04, 232.96) controlPoint2: CGPointMake(98.17, 246.67)];
        [bezier2Path addCurveToPoint: CGPointMake(93.81, 257.59) controlPoint1: CGPointMake(93.87, 251.5) controlPoint2: CGPointMake(92.5, 255.49)];
        [bezier2Path addCurveToPoint: CGPointMake(95.85, 259.06) controlPoint1: CGPointMake(94.26, 258.34) controlPoint2: CGPointMake(94.97, 258.84)];
        [bezier2Path addCurveToPoint: CGPointMake(96.98, 261.23) controlPoint1: CGPointMake(96.53, 259.9) controlPoint2: CGPointMake(97.07, 260.92)];
        [bezier2Path addCurveToPoint: CGPointMake(94.51, 264.99) controlPoint1: CGPointMake(95.61, 262.1) controlPoint2: CGPointMake(94.69, 263.5)];
        [bezier2Path addCurveToPoint: CGPointMake(95.86, 268.64) controlPoint1: CGPointMake(94.36, 266.33) controlPoint2: CGPointMake(94.84, 267.63)];
        [bezier2Path addCurveToPoint: CGPointMake(106.9, 271.63) controlPoint1: CGPointMake(97.43, 270.24) controlPoint2: CGPointMake(102.61, 271.63)];
        [bezier2Path addCurveToPoint: CGPointMake(112.46, 270.45) controlPoint1: CGPointMake(109.24, 271.63) controlPoint2: CGPointMake(111.12, 271.24)];
        [bezier2Path addCurveToPoint: CGPointMake(112.95, 268.9) controlPoint1: CGPointMake(112.99, 270.13) controlPoint2: CGPointMake(113.19, 269.46)];
        [bezier2Path addCurveToPoint: CGPointMake(106.79, 258.75) controlPoint1: CGPointMake(112.87, 268.67) controlPoint2: CGPointMake(110.65, 263.36)];
        [bezier2Path addCurveToPoint: CGPointMake(106.82, 251.45) controlPoint1: CGPointMake(106.58, 257.72) controlPoint2: CGPointMake(105.95, 254.08)];
        [bezier2Path addCurveToPoint: CGPointMake(106.85, 250.83) controlPoint1: CGPointMake(106.9, 251.26) controlPoint2: CGPointMake(106.9, 251.04)];
        [bezier2Path addCurveToPoint: CGPointMake(129.36, 220.35) controlPoint1: CGPointMake(106.82, 250.64) controlPoint2: CGPointMake(103.48, 231.06)];
        [bezier2Path addCurveToPoint: CGPointMake(140.41, 214.8) controlPoint1: CGPointMake(130.23, 220.15) controlPoint2: CGPointMake(135.53, 218.78)];
        [bezier2Path addCurveToPoint: CGPointMake(138.13, 218.38) controlPoint1: CGPointMake(140.12, 216.05) controlPoint2: CGPointMake(139.5, 217.46)];
        [bezier2Path addCurveToPoint: CGPointMake(128.19, 225.32) controlPoint1: CGPointMake(134.46, 220.9) controlPoint2: CGPointMake(128.28, 225.25)];
        [bezier2Path addCurveToPoint: CGPointMake(126.57, 229.58) controlPoint1: CGPointMake(127.37, 226.04) controlPoint2: CGPointMake(126.09, 227.74)];
        [bezier2Path addCurveToPoint: CGPointMake(133.55, 233.87) controlPoint1: CGPointMake(127.09, 231.61) controlPoint2: CGPointMake(129.38, 233.02)];
        [bezier2Path addCurveToPoint: CGPointMake(151.33, 249.06) controlPoint1: CGPointMake(142.85, 235.82) controlPoint2: CGPointMake(150.92, 245.65)];
        [bezier2Path addCurveToPoint: CGPointMake(151.41, 249.41) controlPoint1: CGPointMake(151.34, 249.18) controlPoint2: CGPointMake(151.36, 249.3)];
        [bezier2Path addCurveToPoint: CGPointMake(154.25, 252.75) controlPoint1: CGPointMake(151.63, 249.9) controlPoint2: CGPointMake(152.64, 252.06)];
        [bezier2Path addCurveToPoint: CGPointMake(153.68, 253.72) controlPoint1: CGPointMake(154.16, 253.17) controlPoint2: CGPointMake(153.98, 253.6)];
        [bezier2Path addCurveToPoint: CGPointMake(152.94, 255.01) controlPoint1: CGPointMake(153.17, 253.94) controlPoint2: CGPointMake(152.88, 254.47)];
        [bezier2Path addCurveToPoint: CGPointMake(166.28, 266.16) controlPoint1: CGPointMake(152.99, 255.36) controlPoint2: CGPointMake(154.09, 263.71)];
        [bezier2Path addCurveToPoint: CGPointMake(167.26, 265.92) controlPoint1: CGPointMake(166.62, 266.21) controlPoint2: CGPointMake(166.99, 266.13)];
        [bezier2Path addCurveToPoint: CGPointMake(167.75, 265.04) controlPoint1: CGPointMake(167.54, 265.72) controlPoint2: CGPointMake(167.72, 265.39)];
        [bezier2Path addCurveToPoint: CGPointMake(167.22, 250.32) controlPoint1: CGPointMake(167.86, 263.95) controlPoint2: CGPointMake(168.56, 254.16)];
        [bezier2Path addCurveToPoint: CGPointMake(166.21, 248.46) controlPoint1: CGPointMake(166.85, 249.27) controlPoint2: CGPointMake(166.85, 248.81)];
        [bezier2Path addCurveToPoint: CGPointMake(147.74, 230.13) controlPoint1: CGPointMake(158.17, 244.21) controlPoint2: CGPointMake(152.95, 237.22)];
        [bezier2Path addCurveToPoint: CGPointMake(147.5, 228.09) controlPoint1: CGPointMake(147.56, 229.72) controlPoint2: CGPointMake(147.27, 228.91)];
        [bezier2Path addCurveToPoint: CGPointMake(149.67, 226.01) controlPoint1: CGPointMake(147.74, 227.28) controlPoint2: CGPointMake(148.47, 226.58)];
        [bezier2Path addCurveToPoint: CGPointMake(151.95, 225.02) controlPoint1: CGPointMake(150.31, 225.69) controlPoint2: CGPointMake(151.08, 225.37)];
        [bezier2Path addCurveToPoint: CGPointMake(167.92, 210.12) controlPoint1: CGPointMake(157.1, 222.86) controlPoint2: CGPointMake(165.53, 219.29)];
        [bezier2Path addCurveToPoint: CGPointMake(201.58, 213.83) controlPoint1: CGPointMake(171.26, 210.87) controlPoint2: CGPointMake(186.65, 213.83)];
        [bezier2Path addCurveToPoint: CGPointMake(197.09, 232.16) controlPoint1: CGPointMake(201.58, 213.83) controlPoint2: CGPointMake(197.09, 232.07)];
        [bezier2Path addCurveToPoint: CGPointMake(197.33, 235.7) controlPoint1: CGPointMake(197.09, 232.39) controlPoint2: CGPointMake(197.1, 234.46)];
        [bezier2Path addCurveToPoint: CGPointMake(190.22, 252.81) controlPoint1: CGPointMake(196.27, 242.2) controlPoint2: CGPointMake(191.14, 250.43)];
        [bezier2Path addCurveToPoint: CGPointMake(192.45, 260.45) controlPoint1: CGPointMake(189.08, 255.88) controlPoint2: CGPointMake(190.58, 259.35)];
        [bezier2Path addCurveToPoint: CGPointMake(192.83, 260.72) controlPoint1: CGPointMake(192.68, 260.61) controlPoint2: CGPointMake(192.79, 260.76)];
        [bezier2Path addCurveToPoint: CGPointMake(192.65, 260.85) controlPoint1: CGPointMake(192.8, 260.74) controlPoint2: CGPointMake(192.75, 260.79)];
        [bezier2Path addCurveToPoint: CGPointMake(192.12, 261.52) controlPoint1: CGPointMake(192.4, 261.01) controlPoint2: CGPointMake(192.22, 261.23)];
        [bezier2Path addCurveToPoint: CGPointMake(192.92, 269.21) controlPoint1: CGPointMake(191.73, 262.71) controlPoint2: CGPointMake(190.63, 267.9)];
        [bezier2Path addCurveToPoint: CGPointMake(206.06, 271.48) controlPoint1: CGPointMake(194.25, 269.98) controlPoint2: CGPointMake(200.66, 271.48)];
        [bezier2Path addCurveToPoint: CGPointMake(209.16, 271.12) controlPoint1: CGPointMake(207.21, 271.48) controlPoint2: CGPointMake(208.24, 271.36)];
        [bezier2Path addCurveToPoint: CGPointMake(209.95, 270.49) controlPoint1: CGPointMake(209.51, 271.03) controlPoint2: CGPointMake(209.8, 270.8)];
        [bezier2Path addCurveToPoint: CGPointMake(210.01, 269.49) controlPoint1: CGPointMake(210.12, 270.18) controlPoint2: CGPointMake(210.14, 269.82)];
        [bezier2Path addCurveToPoint: CGPointMake(204.92, 259.37) controlPoint1: CGPointMake(208.54, 265.59) controlPoint2: CGPointMake(206.56, 260.9)];
        [bezier2Path addCurveToPoint: CGPointMake(203.03, 248.39) controlPoint1: CGPointMake(203.25, 255.17) controlPoint2: CGPointMake(202.4, 255.5)];
        [bezier2Path addCurveToPoint: CGPointMake(206.49, 238.26) controlPoint1: CGPointMake(203.46, 243.34) controlPoint2: CGPointMake(206.17, 239.33)];
        [bezier2Path addCurveToPoint: CGPointMake(210.78, 233.11) controlPoint1: CGPointMake(207.82, 237.51) controlPoint2: CGPointMake(209.93, 236.66)];
        [bezier2Path addCurveToPoint: CGPointMake(222.07, 213.92) controlPoint1: CGPointMake(210.99, 231.08) controlPoint2: CGPointMake(219.85, 217.89)];
        [bezier2Path addCurveToPoint: CGPointMake(263.03, 212.82) controlPoint1: CGPointMake(233.03, 213.83) controlPoint2: CGPointMake(245.4, 214.05)];
        [bezier2Path addLineToPoint: CGPointMake(263.43, 216.35)];
        [bezier2Path addCurveToPoint: CGPointMake(257.86, 229.78) controlPoint1: CGPointMake(263, 219.65) controlPoint2: CGPointMake(261.28, 227.68)];
        [bezier2Path addCurveToPoint: CGPointMake(257.28, 231.01) controlPoint1: CGPointMake(257.45, 230.05) controlPoint2: CGPointMake(257.23, 230.52)];
        [bezier2Path addCurveToPoint: CGPointMake(257.13, 233.29) controlPoint1: CGPointMake(257.41, 231.92) controlPoint2: CGPointMake(257.32, 233.09)];
        [bezier2Path addCurveToPoint: CGPointMake(255.45, 232.68) controlPoint1: CGPointMake(256.7, 233.29) controlPoint2: CGPointMake(256.01, 232.97)];
        [bezier2Path addCurveToPoint: CGPointMake(253.25, 231.98) controlPoint1: CGPointMake(254.71, 232.33) controlPoint2: CGPointMake(253.99, 231.98)];
        [bezier2Path addCurveToPoint: CGPointMake(252.06, 232.36) controlPoint1: CGPointMake(252.8, 231.98) controlPoint2: CGPointMake(252.39, 232.11)];
        [bezier2Path addCurveToPoint: CGPointMake(249.71, 249.62) controlPoint1: CGPointMake(250.67, 233.43) controlPoint2: CGPointMake(245.89, 244.01)];
        [bezier2Path addCurveToPoint: CGPointMake(251.31, 250.04) controlPoint1: CGPointMake(250.07, 250.14) controlPoint2: CGPointMake(250.74, 250.31)];
        [bezier2Path addCurveToPoint: CGPointMake(263.77, 240.93) controlPoint1: CGPointMake(252.39, 249.47) controlPoint2: CGPointMake(262.01, 244.46)];
        [bezier2Path addLineToPoint: CGPointMake(266.77, 234.01)];
        [bezier2Path addCurveToPoint: CGPointMake(275.77, 210.67) controlPoint1: CGPointMake(268.4, 225.77) controlPoint2: CGPointMake(275.7, 210.82)];
        [bezier2Path addCurveToPoint: CGPointMake(275.11, 202.92) controlPoint1: CGPointMake(276.1, 209.73) controlPoint2: CGPointMake(277.56, 206.68)];
        [bezier2Path addCurveToPoint: CGPointMake(271.88, 201.05) controlPoint1: CGPointMake(274.38, 201.81) controlPoint2: CGPointMake(273.28, 201.17)];
        [bezier2Path addCurveToPoint: CGPointMake(250.43, 197.72) controlPoint1: CGPointMake(264.23, 200.48) controlPoint2: CGPointMake(252.27, 200.04)];
        [bezier2Path addCurveToPoint: CGPointMake(250.48, 152.19) controlPoint1: CGPointMake(250.5, 185.33) controlPoint2: CGPointMake(250.39, 166.47)];
        [bezier2Path addCurveToPoint: CGPointMake(253.92, 148.44) controlPoint1: CGPointMake(250.52, 152.14) controlPoint2: CGPointMake(253.9, 148.5)];
        [bezier2Path addCurveToPoint: CGPointMake(257.46, 155.78) controlPoint1: CGPointMake(254.45, 149.63) controlPoint2: CGPointMake(255.92, 152.67)];
        [bezier2Path addCurveToPoint: CGPointMake(257.01, 158.29) controlPoint1: CGPointMake(257.18, 156.56) controlPoint2: CGPointMake(257.01, 157.41)];
        [bezier2Path addCurveToPoint: CGPointMake(262.5, 165.28) controlPoint1: CGPointMake(257.01, 161.68) controlPoint2: CGPointMake(259.35, 164.49)];
        [bezier2Path addCurveToPoint: CGPointMake(270.19, 165.48) controlPoint1: CGPointMake(262.53, 165.28) controlPoint2: CGPointMake(266.8, 166.07)];
        [bezier2Path addCurveToPoint: CGPointMake(272.46, 162.91) controlPoint1: CGPointMake(272.12, 165.15) controlPoint2: CGPointMake(272.45, 163.01)];
        [bezier2Path addCurveToPoint: CGPointMake(274.58, 121.23) controlPoint1: CGPointMake(276.18, 146.43) controlPoint2: CGPointMake(276.32, 134.73)];
        [bezier2Path addCurveToPoint: CGPointMake(279.58, 113.58) controlPoint1: CGPointMake(278.17, 116.56) controlPoint2: CGPointMake(279.44, 113.84)];
        [bezier2Path addCurveToPoint: CGPointMake(279.62, 112.4) controlPoint1: CGPointMake(279.79, 113.23) controlPoint2: CGPointMake(279.82, 112.78)];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [VanStyleKit.blancCavall setFill];
        [bezier2Path fill];
    }


    //// Group 2
    {
        //// Bezier 4 Drawing
        UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
        [bezier4Path moveToPoint: CGPointMake(28.41, 497.63)];
        [bezier4Path addLineToPoint: CGPointMake(12.28, 497.63)];
        [bezier4Path addLineToPoint: CGPointMake(12.28, 570.7)];
        [bezier4Path addLineToPoint: CGPointMake(64.77, 570.7)];
        [bezier4Path addLineToPoint: CGPointMake(64.77, 555.9)];
        [bezier4Path addLineToPoint: CGPointMake(28.41, 555.9)];
        [bezier4Path addLineToPoint: CGPointMake(28.41, 497.63)];
        [bezier4Path closePath];
        bezier4Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier4Path fill];


        //// Rectangle 4 Drawing
        UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRect: CGRectMake(72.37, 497.63, 15.99, 73.06)];
        [VanStyleKit.lletraEquus setFill];
        [rectangle4Path fill];


        //// Bezier 6 Drawing
        UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
        [bezier6Path moveToPoint: CGPointMake(101.45, 570.7)];
        [bezier6Path addLineToPoint: CGPointMake(117.54, 570.7)];
        [bezier6Path addLineToPoint: CGPointMake(117.54, 542.3)];
        [bezier6Path addLineToPoint: CGPointMake(152.2, 542.3)];
        [bezier6Path addLineToPoint: CGPointMake(152.2, 527.73)];
        [bezier6Path addLineToPoint: CGPointMake(117.54, 527.73)];
        [bezier6Path addLineToPoint: CGPointMake(117.54, 512.25)];
        [bezier6Path addLineToPoint: CGPointMake(156.96, 512.25)];
        [bezier6Path addLineToPoint: CGPointMake(156.96, 497.63)];
        [bezier6Path addLineToPoint: CGPointMake(101.45, 497.63)];
        [bezier6Path addLineToPoint: CGPointMake(101.45, 570.7)];
        [bezier6Path closePath];
        bezier6Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier6Path fill];


        //// Bezier 8 Drawing
        UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
        [bezier8Path moveToPoint: CGPointMake(180.49, 541)];
        [bezier8Path addLineToPoint: CGPointMake(214.89, 541)];
        [bezier8Path addLineToPoint: CGPointMake(214.89, 526.73)];
        [bezier8Path addLineToPoint: CGPointMake(180.49, 526.73)];
        [bezier8Path addLineToPoint: CGPointMake(180.49, 511.93)];
        [bezier8Path addLineToPoint: CGPointMake(219.48, 511.93)];
        [bezier8Path addLineToPoint: CGPointMake(219.48, 497.63)];
        [bezier8Path addLineToPoint: CGPointMake(164.57, 497.63)];
        [bezier8Path addLineToPoint: CGPointMake(164.57, 570.7)];
        [bezier8Path addLineToPoint: CGPointMake(220.1, 570.7)];
        [bezier8Path addLineToPoint: CGPointMake(220.1, 556.39)];
        [bezier8Path addLineToPoint: CGPointMake(180.49, 556.39)];
        [bezier8Path addLineToPoint: CGPointMake(180.49, 541)];
        [bezier8Path closePath];
        bezier8Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier8Path fill];


        //// Bezier 10 Drawing
        UIBezierPath* bezier10Path = UIBezierPath.bezierPath;
        [bezier10Path moveToPoint: CGPointMake(28.18, 452.06)];
        [bezier10Path addLineToPoint: CGPointMake(62.59, 452.06)];
        [bezier10Path addLineToPoint: CGPointMake(62.59, 437.78)];
        [bezier10Path addLineToPoint: CGPointMake(28.18, 437.78)];
        [bezier10Path addLineToPoint: CGPointMake(28.18, 423.02)];
        [bezier10Path addLineToPoint: CGPointMake(67.35, 423.02)];
        [bezier10Path addLineToPoint: CGPointMake(67.35, 408.72)];
        [bezier10Path addLineToPoint: CGPointMake(12.28, 408.72)];
        [bezier10Path addLineToPoint: CGPointMake(12.28, 481.64)];
        [bezier10Path addLineToPoint: CGPointMake(67.8, 481.64)];
        [bezier10Path addLineToPoint: CGPointMake(67.8, 467.39)];
        [bezier10Path addLineToPoint: CGPointMake(28.18, 467.39)];
        [bezier10Path addLineToPoint: CGPointMake(28.18, 452.06)];
        [bezier10Path closePath];
        bezier10Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier10Path fill];


        //// Bezier 12 Drawing
        UIBezierPath* bezier12Path = UIBezierPath.bezierPath;
        [bezier12Path moveToPoint: CGPointMake(206.6, 450.53)];
        [bezier12Path addCurveToPoint: CGPointMake(190.79, 468.02) controlPoint1: CGPointMake(206.6, 462.01) controlPoint2: CGPointMake(200.76, 468.02)];
        [bezier12Path addCurveToPoint: CGPointMake(175.16, 449.93) controlPoint1: CGPointMake(181.1, 468.02) controlPoint2: CGPointMake(175.16, 461.89)];
        [bezier12Path addLineToPoint: CGPointMake(175.16, 408.72)];
        [bezier12Path addLineToPoint: CGPointMake(158.98, 408.72)];
        [bezier12Path addLineToPoint: CGPointMake(158.98, 450.37)];
        [bezier12Path addCurveToPoint: CGPointMake(190.65, 482.88) controlPoint1: CGPointMake(158.98, 471.87) controlPoint2: CGPointMake(171.14, 482.88)];
        [bezier12Path addCurveToPoint: CGPointMake(222.65, 449.93) controlPoint1: CGPointMake(210.36, 482.88) controlPoint2: CGPointMake(222.65, 471.96)];
        [bezier12Path addLineToPoint: CGPointMake(222.65, 408.72)];
        [bezier12Path addLineToPoint: CGPointMake(206.6, 408.72)];
        [bezier12Path addLineToPoint: CGPointMake(206.6, 450.53)];
        [bezier12Path addLineToPoint: CGPointMake(206.6, 450.53)];
        [bezier12Path closePath];
        bezier12Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier12Path fill];


        //// Bezier 14 Drawing
        UIBezierPath* bezier14Path = UIBezierPath.bezierPath;
        [bezier14Path moveToPoint: CGPointMake(280.11, 450.53)];
        [bezier14Path addCurveToPoint: CGPointMake(264.37, 468.02) controlPoint1: CGPointMake(280.11, 462.01) controlPoint2: CGPointMake(274.22, 468.02)];
        [bezier14Path addCurveToPoint: CGPointMake(248.63, 449.93) controlPoint1: CGPointMake(254.67, 468.02) controlPoint2: CGPointMake(248.63, 461.89)];
        [bezier14Path addLineToPoint: CGPointMake(248.63, 408.72)];
        [bezier14Path addLineToPoint: CGPointMake(232.58, 408.72)];
        [bezier14Path addLineToPoint: CGPointMake(232.58, 450.37)];
        [bezier14Path addCurveToPoint: CGPointMake(264.26, 482.88) controlPoint1: CGPointMake(232.58, 471.87) controlPoint2: CGPointMake(244.6, 482.88)];
        [bezier14Path addCurveToPoint: CGPointMake(296.27, 449.93) controlPoint1: CGPointMake(283.84, 482.88) controlPoint2: CGPointMake(296.27, 471.96)];
        [bezier14Path addLineToPoint: CGPointMake(296.27, 408.72)];
        [bezier14Path addLineToPoint: CGPointMake(280.11, 408.72)];
        [bezier14Path addLineToPoint: CGPointMake(280.11, 450.53)];
        [bezier14Path closePath];
        bezier14Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier14Path fill];


        //// Bezier 16 Drawing
        UIBezierPath* bezier16Path = UIBezierPath.bezierPath;
        [bezier16Path moveToPoint: CGPointMake(337.03, 438.02)];
        [bezier16Path addCurveToPoint: CGPointMake(321.2, 428.39) controlPoint1: CGPointMake(324.38, 434.74) controlPoint2: CGPointMake(321.2, 433.25)];
        [bezier16Path addLineToPoint: CGPointMake(321.2, 428.17)];
        [bezier16Path addCurveToPoint: CGPointMake(330.54, 421.75) controlPoint1: CGPointMake(321.2, 424.63) controlPoint2: CGPointMake(324.44, 421.75)];
        [bezier16Path addCurveToPoint: CGPointMake(349.6, 429.01) controlPoint1: CGPointMake(336.7, 421.75) controlPoint2: CGPointMake(343.07, 424.59)];
        [bezier16Path addLineToPoint: CGPointMake(357.86, 416.96)];
        [bezier16Path addCurveToPoint: CGPointMake(330.76, 407.69) controlPoint1: CGPointMake(350.5, 410.99) controlPoint2: CGPointMake(341.35, 407.69)];
        [bezier16Path addCurveToPoint: CGPointMake(305.23, 429.65) controlPoint1: CGPointMake(315.89, 407.69) controlPoint2: CGPointMake(305.23, 416.34)];
        [bezier16Path addLineToPoint: CGPointMake(305.23, 429.88)];
        [bezier16Path addCurveToPoint: CGPointMake(329.47, 452.18) controlPoint1: CGPointMake(305.23, 444.44) controlPoint2: CGPointMake(314.71, 448.42)];
        [bezier16Path addCurveToPoint: CGPointMake(344.18, 461.54) controlPoint1: CGPointMake(341.62, 455.27) controlPoint2: CGPointMake(344.18, 457.42)];
        [bezier16Path addLineToPoint: CGPointMake(344.18, 461.73)];
        [bezier16Path addCurveToPoint: CGPointMake(333.65, 468.47) controlPoint1: CGPointMake(344.18, 465.93) controlPoint2: CGPointMake(340.14, 468.47)];
        [bezier16Path addCurveToPoint: CGPointMake(311.87, 459.66) controlPoint1: CGPointMake(325.28, 468.47) controlPoint2: CGPointMake(318.38, 465.06)];
        [bezier16Path addLineToPoint: CGPointMake(302.35, 471.02)];
        [bezier16Path addCurveToPoint: CGPointMake(333.38, 482.74) controlPoint1: CGPointMake(311.2, 478.82) controlPoint2: CGPointMake(322.23, 482.74)];
        [bezier16Path addCurveToPoint: CGPointMake(360.12, 460.08) controlPoint1: CGPointMake(349.07, 482.74) controlPoint2: CGPointMake(360.12, 474.58)];
        [bezier16Path addLineToPoint: CGPointMake(360.12, 459.91)];
        [bezier16Path addCurveToPoint: CGPointMake(337.03, 438.02) controlPoint1: CGPointMake(360.12, 447.2) controlPoint2: CGPointMake(351.74, 441.82)];
        [bezier16Path closePath];
        bezier16Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier16Path fill];


        //// Bezier 18 Drawing
        UIBezierPath* bezier18Path = UIBezierPath.bezierPath;
        [bezier18Path moveToPoint: CGPointMake(112.34, 482.92)];
        [bezier18Path addCurveToPoint: CGPointMake(132.07, 477.95) controlPoint1: CGPointMake(119.67, 482.92) controlPoint2: CGPointMake(126.37, 481.1)];
        [bezier18Path addLineToPoint: CGPointMake(135.9, 482.2)];
        [bezier18Path addLineToPoint: CGPointMake(155.12, 482.2)];
        [bezier18Path addLineToPoint: CGPointMake(143.07, 468.74)];
        [bezier18Path addCurveToPoint: CGPointMake(151.35, 445.16) controlPoint1: CGPointMake(148.31, 462.26) controlPoint2: CGPointMake(151.35, 454.06)];
        [bezier18Path addLineToPoint: CGPointMake(151.35, 444.9)];
        [bezier18Path addCurveToPoint: CGPointMake(112.49, 407.45) controlPoint1: CGPointMake(151.35, 424.28) controlPoint2: CGPointMake(135.09, 407.45)];
        [bezier18Path addCurveToPoint: CGPointMake(73.6, 445.16) controlPoint1: CGPointMake(90.02, 407.45) controlPoint2: CGPointMake(73.6, 424.49)];
        [bezier18Path addLineToPoint: CGPointMake(73.6, 445.44)];
        [bezier18Path addCurveToPoint: CGPointMake(112.34, 482.92) controlPoint1: CGPointMake(73.6, 466.21) controlPoint2: CGPointMake(89.77, 482.92)];
        [bezier18Path closePath];
        [bezier18Path moveToPoint: CGPointMake(90.48, 444.9)];
        [bezier18Path addCurveToPoint: CGPointMake(112.34, 422.27) controlPoint1: CGPointMake(90.48, 432.47) controlPoint2: CGPointMake(99.34, 422.27)];
        [bezier18Path addCurveToPoint: CGPointMake(134.34, 445.16) controlPoint1: CGPointMake(125.17, 422.27) controlPoint2: CGPointMake(134.34, 432.65)];
        [bezier18Path addLineToPoint: CGPointMake(134.34, 445.44)];
        [bezier18Path addCurveToPoint: CGPointMake(112.49, 468.12) controlPoint1: CGPointMake(134.34, 457.87) controlPoint2: CGPointMake(125.53, 468.12)];
        [bezier18Path addCurveToPoint: CGPointMake(90.48, 445.16) controlPoint1: CGPointMake(99.63, 468.12) controlPoint2: CGPointMake(90.48, 457.67)];
        [bezier18Path addLineToPoint: CGPointMake(90.48, 444.9)];
        [bezier18Path closePath];
        bezier18Path.miterLimit = 4;

        [VanStyleKit.lletraEquus setFill];
        [bezier18Path fill];
    }
}

+ (void)drawFichaA5;
{

    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(134.8, 70.58)];
    [bezier2Path addLineToPoint: CGPointMake(133.63, 67.17)];
    [bezier2Path addCurveToPoint: CGPointMake(129.02, 63.75) controlPoint1: CGPointMake(132.98, 65.28) controlPoint2: CGPointMake(130.92, 63.75)];
    [bezier2Path addLineToPoint: CGPointMake(124.76, 63.75)];
    [bezier2Path addCurveToPoint: CGPointMake(116.52, 41.52) controlPoint1: CGPointMake(121.56, 54.82) controlPoint2: CGPointMake(117.65, 44.05)];
    [bezier2Path addCurveToPoint: CGPointMake(106, 34.96) controlPoint1: CGPointMake(114.75, 37.6) controlPoint2: CGPointMake(109.1, 35.83)];
    [bezier2Path addCurveToPoint: CGPointMake(83.5, 33) controlPoint1: CGPointMake(106, 34.96) controlPoint2: CGPointMake(100.81, 33)];
    [bezier2Path addCurveToPoint: CGPointMake(61.01, 34.96) controlPoint1: CGPointMake(66.2, 33) controlPoint2: CGPointMake(61.01, 34.96)];
    [bezier2Path addCurveToPoint: CGPointMake(50.3, 41.7) controlPoint1: CGPointMake(57.37, 36.17) controlPoint2: CGPointMake(52.31, 37.88)];
    [bezier2Path addCurveToPoint: CGPointMake(42.16, 63.75) controlPoint1: CGPointMake(49.36, 43.49) controlPoint2: CGPointMake(45.39, 54.57)];
    [bezier2Path addLineToPoint: CGPointMake(37.98, 63.75)];
    [bezier2Path addCurveToPoint: CGPointMake(33.38, 67.17) controlPoint1: CGPointMake(36.09, 63.75) controlPoint2: CGPointMake(34.03, 65.28)];
    [bezier2Path addLineToPoint: CGPointMake(32.2, 70.58)];
    [bezier2Path addCurveToPoint: CGPointMake(34.45, 74) controlPoint1: CGPointMake(31.55, 72.47) controlPoint2: CGPointMake(32.56, 74)];
    [bezier2Path addLineToPoint: CGPointMake(38.57, 74)];
    [bezier2Path addCurveToPoint: CGPointMake(37.72, 76.46) controlPoint1: CGPointMake(38.04, 75.53) controlPoint2: CGPointMake(37.72, 76.46)];
    [bezier2Path addCurveToPoint: CGPointMake(37.15, 80.26) controlPoint1: CGPointMake(37.39, 77.02) controlPoint2: CGPointMake(37.15, 79.58)];
    [bezier2Path addLineToPoint: CGPointMake(37.15, 99.62)];
    [bezier2Path addLineToPoint: CGPointMake(37.15, 100.97)];
    [bezier2Path addLineToPoint: CGPointMake(37.15, 111.38)];
    [bezier2Path addCurveToPoint: CGPointMake(40.79, 115) controlPoint1: CGPointMake(37.15, 113.38) controlPoint2: CGPointMake(38.78, 115)];
    [bezier2Path addLineToPoint: CGPointMake(54.11, 115)];
    [bezier2Path addCurveToPoint: CGPointMake(57.75, 111.38) controlPoint1: CGPointMake(56.12, 115) controlPoint2: CGPointMake(57.75, 113.38)];
    [bezier2Path addLineToPoint: CGPointMake(57.75, 104.75)];
    [bezier2Path addLineToPoint: CGPointMake(109.25, 104.75)];
    [bezier2Path addLineToPoint: CGPointMake(109.25, 111.38)];
    [bezier2Path addCurveToPoint: CGPointMake(112.88, 115) controlPoint1: CGPointMake(109.25, 113.38) controlPoint2: CGPointMake(110.88, 115)];
    [bezier2Path addLineToPoint: CGPointMake(126.21, 115)];
    [bezier2Path addCurveToPoint: CGPointMake(129.85, 111.38) controlPoint1: CGPointMake(128.22, 115) controlPoint2: CGPointMake(129.85, 113.38)];
    [bezier2Path addLineToPoint: CGPointMake(129.85, 100.97)];
    [bezier2Path addLineToPoint: CGPointMake(129.85, 99.62)];
    [bezier2Path addLineToPoint: CGPointMake(129.85, 80.26)];
    [bezier2Path addCurveToPoint: CGPointMake(129.28, 76.46) controlPoint1: CGPointMake(129.85, 79.57) controlPoint2: CGPointMake(129.61, 77.02)];
    [bezier2Path addCurveToPoint: CGPointMake(128.41, 74) controlPoint1: CGPointMake(129.28, 76.46) controlPoint2: CGPointMake(128.95, 75.53)];
    [bezier2Path addLineToPoint: CGPointMake(132.55, 74)];
    [bezier2Path addCurveToPoint: CGPointMake(134.8, 70.58) controlPoint1: CGPointMake(134.44, 74) controlPoint2: CGPointMake(135.45, 72.47)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(57.67, 89.64)];
    [bezier2Path addLineToPoint: CGPointMake(52.16, 89.64)];
    [bezier2Path addCurveToPoint: CGPointMake(42.3, 85.87) controlPoint1: CGPointMake(47.23, 89.64) controlPoint2: CGPointMake(42.3, 88.98)];
    [bezier2Path addLineToPoint: CGPointMake(42.3, 82.09)];
    [bezier2Path addCurveToPoint: CGPointMake(46.72, 78.32) controlPoint1: CGPointMake(42.3, 78.45) controlPoint2: CGPointMake(44.43, 78.32)];
    [bezier2Path addCurveToPoint: CGPointMake(56.31, 81.5) controlPoint1: CGPointMake(48.96, 78.32) controlPoint2: CGPointMake(53.39, 80.2)];
    [bezier2Path addCurveToPoint: CGPointMake(63.06, 86.46) controlPoint1: CGPointMake(59.5, 82.92) controlPoint2: CGPointMake(63.06, 84.1)];
    [bezier2Path addCurveToPoint: CGPointMake(57.67, 89.64) controlPoint1: CGPointMake(63.06, 88.64) controlPoint2: CGPointMake(61.83, 89.64)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(50, 65.13)];
    [bezier2Path addCurveToPoint: CGPointMake(56.31, 45.83) controlPoint1: CGPointMake(52.71, 53.92) controlPoint2: CGPointMake(55.65, 47.6)];
    [bezier2Path addCurveToPoint: CGPointMake(83.5, 40.59) controlPoint1: CGPointMake(56.82, 44.55) controlPoint2: CGPointMake(57.33, 40.59)];
    [bezier2Path addCurveToPoint: CGPointMake(110.35, 45.16) controlPoint1: CGPointMake(109.67, 40.59) controlPoint2: CGPointMake(110.29, 45.11)];
    [bezier2Path addCurveToPoint: CGPointMake(116.92, 65.12) controlPoint1: CGPointMake(111.16, 47.56) controlPoint2: CGPointMake(114.36, 54.8)];
    [bezier2Path addCurveToPoint: CGPointMake(83.5, 68.87) controlPoint1: CGPointMake(116.92, 65.12) controlPoint2: CGPointMake(105.87, 68.87)];
    [bezier2Path addCurveToPoint: CGPointMake(50, 65.13) controlPoint1: CGPointMake(61.12, 68.87) controlPoint2: CGPointMake(50, 65.13)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(103.94, 86.46)];
    [bezier2Path addCurveToPoint: CGPointMake(110.68, 81.5) controlPoint1: CGPointMake(103.94, 84.09) controlPoint2: CGPointMake(107.5, 82.91)];
    [bezier2Path addCurveToPoint: CGPointMake(120.28, 78.31) controlPoint1: CGPointMake(113.6, 80.2) controlPoint2: CGPointMake(118.04, 78.31)];
    [bezier2Path addCurveToPoint: CGPointMake(124.69, 82.09) controlPoint1: CGPointMake(122.57, 78.31) controlPoint2: CGPointMake(124.69, 78.44)];
    [bezier2Path addLineToPoint: CGPointMake(124.69, 85.87)];
    [bezier2Path addLineToPoint: CGPointMake(124.7, 85.87)];
    [bezier2Path addCurveToPoint: CGPointMake(114.84, 89.64) controlPoint1: CGPointMake(124.7, 88.99) controlPoint2: CGPointMake(119.77, 89.64)];
    [bezier2Path addLineToPoint: CGPointMake(109.32, 89.64)];
    [bezier2Path addCurveToPoint: CGPointMake(103.94, 86.46) controlPoint1: CGPointMake(105.17, 89.64) controlPoint2: CGPointMake(103.94, 88.64)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    [UIColor.blackColor setFill];
    [bezier2Path fill];


    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(16, 150)];
    [bezierPath addLineToPoint: CGPointMake(150, 150)];
    [UIColor.blackColor setFill];
    [bezierPath fill];


    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(17, 150, 134, 15)];
    [VanStyleKit.negre setFill];
    [rectanglePath fill];


    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(17, 188, 134, 15)];
    [VanStyleKit.negre setFill];
    [rectangle2Path fill];
}

+ (void)drawCanvas2;
{
}

@end
