//
//  VanStyleKit.h
//  VAN Selector
//
//  Created by Marc Humet on 23/10/14.
//  Copyright (c) 2014 EQUUS LIFE SL. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface VanStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* fichaB5Targets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* fichaA4Targets;

// Colors
+ (UIColor*)lletraEquus;
+ (UIColor*)vermellEquus;
+ (UIColor*)blancCavall;
+ (UIColor*)negre;

// Drawing Methods
+ (void)drawLogoEquusHoritzontalWithFrame: (CGRect)frame;
+ (void)drawLogoEquusVerticalWithFrame: (CGRect)frame;
+ (void)drawLogoChevalWithFrame: (CGRect)frame;
+ (void)drawCarNavIconWithFrame: (CGRect)frame;
+ (void)drawTrailerWithColorParameter: (UIColor*)colorParameter scale: (CGFloat)scale;
+ (void)drawHorseWithFrame: (CGRect)frame;
+ (void)drawEquusHorseWithColorParameter: (UIColor*)colorParameter scale: (CGFloat)scale;
+ (void)drawLicenceIconWithColorParameter: (UIColor*)colorParameter scale: (CGFloat)scale;
+ (void)drawIconoLicenceSoloWithFrame: (CGRect)frame colorParameter: (UIColor*)colorParameter;
+ (void)drawMap;
+ (void)drawCalculationResults1WithMmaVan: (NSString*)mmaVan mmaCar: (NSString*)mmaCar numHorses: (NSString*)numHorses licence: (NSString*)licence sumaMMAs: (NSString*)sumaMMAs;
+ (void)drawEquusHorseNavBar;
+ (void)drawTrailerMaxPtac;
+ (void)drawLicenceNavIcon;
+ (void)drawCarWithColorParameter: (UIColor*)colorParameter scale: (CGFloat)scale;
+ (void)drawCalculationResults2WithMmaVan: (NSString*)mmaVan numHorses: (NSString*)numHorses weightHorse: (NSString*)weightHorse weightHorses: (NSString*)weightHorses weightTrailer: (NSString*)weightTrailer weightTrailerAndHorses: (NSString*)weightTrailerAndHorses;
+ (void)drawFichaB5;
+ (void)drawFichaA4;
+ (void)drawMenuBackgroundWithFrame: (CGRect)frame;
+ (void)drawLicenceMenuButton;
+ (void)drawCatalogMenuButton;
+ (void)drawMApMenuButton;

// Generated Images
+ (UIImage*)imageOfFichaB5;
+ (UIImage*)imageOfFichaA4;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
